### ISSUE TITLE
Does not work when using S3 storage

### ISSUE THREAD

**Issue by JanMisker** [redon2/strapi-plugin-pdf-creator#4]
When testing I found out that this plugin doesn't work when using S3 storage.
I'm not sure if it is when reading the template file or when writing the resulting PDF.
Error message:
`
Error: ENOENT: no such file or directory, open 'publichttps://XXX-my-bucket.digitaloceanspaces.com/test_0ba938dd88.pdf'
`
With this line as origin of the error:
`
    at Object.create (/XXX-my-path/node_modules/@redon2inc/strapi-plugin-pdf-creator/dist/server/index.js:147:32)
`

Perhaps you are bypassing the Upload Plugin API?

**Comment by redondi88** [comment]
Yes, thanks for reminding me that I need to update the docs.
My use case was for local only, so never bothered with S3.

**Comment by JanMisker** [comment]
Ah that's a pity. I will have a look maybe I submit a pull request.

**Comment by JanMisker** [comment]
@redondi88 you saw the pull request? #5
